<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vivek" failures="0" tests="5" name="Test02" time="183.639" errors="0" timestamp="29 Oct 2023 06:45:59 GMT">
  <testcase classname="org.practice.Adactin" name="@BeforeClass startingSetup" time="183.559">
    <failure type="org.openqa.selenium.TimeoutException" message="java.util.concurrent.TimeoutException
Build info: version: &amp;apos;4.10.0&amp;apos;, revision: &amp;apos;c14d967899&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;17.0.7&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [9f1653cea1b333cab03207427ae09c6e, get {url=https://adactinhotelapp.com/}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.118, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: C:\Users\vlviv\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54866}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:54866/devtoo..., se:cdpVersion: 118.0.5993.118, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9f1653cea1b333cab03207427ae09c6e">
      <![CDATA[org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.7'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [9f1653cea1b333cab03207427ae09c6e, get {url=https://adactinhotelapp.com/}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.118, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: C:\Users\vlviv\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:54866}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:54866/devtoo..., se:cdpVersion: 118.0.5993.118, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9f1653cea1b333cab03207427ae09c6e
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:65)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:97)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:188)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:295)
at org.base.BaseClass.LoadUrl(BaseClass.java:51)
at org.practice.Adactin.startingSetup(Adactin.java:47)
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
... 39 more
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass startingSetup -->
  <testcase classname="org.practice.Adactin" name="@AfterMethod takeShot" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod takeShot -->
  <testcase classname="org.practice.Adactin" name="@AfterMethod takeShot" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod takeShot -->
  <testcase classname="org.practice.Adactin" name="@AfterMethod takeShot" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod takeShot -->
  <testcase classname="org.practice.Adactin" name="@AfterMethod takeShot" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod takeShot -->
  <testcase classname="org.practice.Adactin" name="@AfterMethod takeShot" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod takeShot -->
  <testcase classname="org.practice.Adactin" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="org.practice.Adactin" name="verifyLogo" time="0.0">
    <skipped/>
  </testcase> <!-- verifyLogo -->
  <testcase classname="org.practice.Adactin" name="login" time="0.0">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="org.practice.Adactin" name="search" time="0.0">
    <skipped/>
  </testcase> <!-- search -->
  <testcase classname="org.practice.Adactin" name="select" time="0.0">
    <skipped/>
  </testcase> <!-- select -->
  <testcase classname="org.practice.Adactin" name="book" time="0.0">
    <skipped/>
  </testcase> <!-- book -->
</testsuite> <!-- Test02 -->
